name: Build and Deploy

on:
  - push

jobs:
  apple:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.2'
    - run: flutter config --enable-macos-desktop
    - run: flutter create demo
    - run: cd demo && ls -l && pwd
    - run: cd demo && flutter build ios --release --no-codesign
    - run: cd demo && flutter build macos
    - uses: actions/upload-artifact@v2
      with:
        name: bundle.zip
        path: demo