name: Build and Deploy

on:
  - push

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update
    - run: git clone https://github.com/bevyengine/bevy.git
    - run: cd bevy && cargo build --release --example bevymark
    - uses: actions/upload-artifact@v2
      with:
        name: bevymark
        path: bevy/target/release/examples/bevymark