name: Build and Deploy

on:
  - push

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update
    - run: git clone https://github.com/gfx-rs/wgpu.git
    - run: cd wgpu/wgpu && cargo build --release --example cube
    - uses: actions/upload-artifact@v2
      with:
        name: wgpu
        path: wgpu/target/release/examples
